
spring:
  datasource:
    url: jdbc:mysql://test_database:3306/dockerlizationdb?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect=true
    show-sql: true
    generate-ddl: true